# Generated by Django 3.2.12 on 2024-06-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
