# Generated by Django 3.2.12 on 2024-06-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20240610_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Optedtb',
        ),
    ]
